import Head from 'next/head'
import { Button } from '../styles/styled/button'

export default function Home() {
  return (
    <>
      <Head>
        <title>聚會趣</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello,world</h1>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <Button>我是按鈕</Button>
      <Button $primary={true}>我是按鈕</Button>
    </>
  )
}
